nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
    - 'arm64'
